In [12]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math
import os

In [4]:
print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
C:\Users\Gabriel\Desktop\New folder (5)

In [5]:
label = pd.read_excel('label.xlsx') #Taxa de população economicamente ativa
government = pd.read_excel('government.xlsx') #Per capita government expenditure on health at average exchange rate (US$)
expenditure = pd.read_excel('expenditure.xlsx') #Expenditure per student, primary (% of GDP per capita)

# Todos os dados são referentes ao ano de 2007

In [22]:
Data_Total = pd.DataFrame()
desemprego_dados = list(label.Paises)
government_list = []
expenditure_list = []
filtered_list = []

government_indices = []
label_indices = []
expenditure_indices = []

label_num = []
government_num = []
expenditure_num = []

for element in range(len(expenditure.Paises)):    
    if expenditure.Paises[element] in desemprego_dados:
        expenditure_list.append(expenditure.Paises[element])
        expenditure_indices.append(element)
for element in range(len(government.Paises)):    
    if government.Paises[element] in desemprego_dados:
        government_list.append(government.Paises[element]) 
        government_indices.append(element)
if len(government_list) < len(expenditure_list):
    for element in range(len(government_list)):    
        if government_list[element] in expenditure_list:
            filtered_list.append(government_list[element])  
else:
    for element in range(len(expenditure_list)):    
        if expenditure_list[element] in government_list:
            filtered_list.append(expenditure_list[element])

for element in filtered_list:    
    label_indices.append(desemprego_dados.index(element))
    
for element in range(len(filtered_list)):    
    label_num.append(label.year[label_indices[element]])     

for element in range(len(filtered_list)):    
    government_num.append(government.year[government_indices[element]])  

for element in range(len(filtered_list)):    
    expenditure_num.append(expenditure.year[expenditure_indices[element]])      

Data_Total["Paises"] = filtered_list  
Data_Total["Label"] = label_num  
Data_Total["Government"] = government_num        
Data_Total["Expenditure"] = expenditure_num

Data_Total= Data_Total[~np.isnan(Data_Total.Label)]
Data_Total= Data_Total[~np.isnan(Data_Total.Government)]
Data_Total= Data_Total[~np.isnan(Data_Total.Expenditure)]

Data_Total

                    Paises      Label   Government  Expenditure
4                Argentina  49.700001   333.859695    14.639570
6                Australia  57.400002  2670.987968    16.407640
7                  Austria  52.299999  3517.034374    22.989220
11              Bangladesh  57.200001    47.405185    10.312540
14                 Belgium  45.700001  3065.374217    20.496240
20                Botswana  48.200001   386.012410    12.621320
21                  Brazil  59.500000   255.086881    17.265890
23                Bulgaria  45.500000   218.073433    22.088180
24            Burkina Faso  77.099998    17.964199    29.691270
27                Cameroon  52.400002    11.866852     7.233040
29              Cape Verde  46.500000   103.043208    15.463470
30                    Chad  71.000000     6.595634     5.299110
32                   China  70.599998    53.725777    11.925300
34                 Comoros  63.200001    19.101922    12.458230
40                    Cuba  44.700001   556.631710    20.856212
41                  Cyprus  53.700001   713.055633    45.641380
42                 Denmark  60.599998  4800.050817    26.453050
43                Djibouti  57.799999    53.937541    13.023410
44                 Ecuador  52.099998    55.452385    24.435780
45                   Egypt  23.799999    34.881159    23.677910
46             El Salvador  46.500000   122.294033     9.031740
49                 Estonia  54.200001   638.920881     8.042510
52                 Finland  57.599998  2783.914137    19.717640
56                  Gambia  70.099998   102.543655    18.295240
61                    Guam  55.599998  1615.576642    15.659310
65                  Guyana  47.599998     1.825460    10.276430
68        Hong Kong, China  53.400002     8.244462     8.744590
71                   India  34.200001   719.581746    12.505010
72               Indonesia  49.599998  5120.754384    25.389050
73                    Iran  31.799999    10.423702    26.135410
..                     ...        ...          ...          ...
92          Macedonia, FYR  41.799999   224.329580     5.478570
94                  Malawi  76.300003  6414.460517    15.815210
98                   Malta  32.599998    12.700101     9.117420
100              Mauritius  42.400002   221.860474    11.779110
106                Myanmar  69.199997   256.133460    13.609000
107                Namibia  48.799999    60.532757    31.619860
108                  Nepal  59.000000    48.547644    13.743530
109            Netherlands  56.599998    45.560665    14.529940
114                Nigeria  38.700001  3478.576893    16.812750
118                 Panama  47.900002    50.835990    31.831210
120               Paraguay  70.699997    26.824885    18.478880
123                 Poland  47.000000     6.919198    12.440040
125            Puerto Rico  38.299999    23.152854    10.737600
126                  Qatar  41.400002    49.162430     7.223740
127                Romania  46.299999   113.264089     8.658640
128                 Russia  57.099998    19.916013    24.336710
132           Saudi Arabia  19.100000  1314.775767    19.987500
134           Sierra Leone  64.900002   341.815940     9.058810
136        Slovak Republic  51.799999    17.161177    20.156890
139                Somalia  54.299999   408.893586    19.326810
143                  Sudan  31.299999   366.657478    15.647490
148                  Syria  20.900000   202.196970    19.383130
153                   Togo  51.799999    97.876037    24.986090
154                  Tonga  52.900002  3667.941643    22.511290
155    Trinidad and Tobago  55.000000  3586.185573    17.375590
159                 Uganda  81.599998    99.104269    27.583034
160                Ukraine  52.799999    42.973998     8.335860
162         United Kingdom  55.799999   174.222603     8.687120
169  Virgin Islands (U.S.)  57.900002   717.998024    22.983160
170     West Bank and Gaza  14.000000  3156.501937    22.028130

[69 rows x 4 columns]

<img src="2007_a.png" style="width:304px;height:228px;">

<img src="2007_b.png" style="width:304px;height:228px;">